title: Fino Sabor
description: Fino Sabor
url: http://localhost:4000
#url: https://uiot.github.io/Enterprise
permalink: /blog/:categories/:year/:month/:day/:title.html
markdown: kramdown
gems:
  - jekyll-feed
#  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
